### ISSUE TITLE
Unable to add latest dependency com.instamojo:android-sdk:3.7.0

### ISSUE THREAD

**Issue by oneplusreddy** [Instamojo/instamojo-android-sdk#106]
Getting "Internal error: Artifact type null not expected, only jar or aar are handled." while adding dependency "implementation 'com.instamojo:android-sdk:3.7.0'"

**Comment by kmvora13990** [comment]
Hello Instamojo Team,

Because of this issue, I am unable to add this version into my Gradle file dependency. pPlease resolve this issue as soon as possible.

its more than month, I hope that you will resolve it soon.

**Comment by SiddharthRana** [comment]
Hello, sorry for the late reply. You can use the dependency like
`implementation ('com.instamojo:android-sdk:3.7.0@aar') {
        transitive = true
}`
This should work.

Also if you come across the duplicate class error, dont forget to add `android.enableJetifier=true` in your `gradle.properties` file.
Thank you.

**Comment by grvsingh44** [comment]
Thanks for update. But if some one update your docs it will be much better for us to stop wasting time.

**Comment by vijayakumarksv** [comment]
> implementation ('com.instamojo:android-sdk:3.7.0@aar') { transitive = true }

After adding above line in the gradle , we are trying to build app but we were facing build failure issue.

Failed to resolve: in.juspay:godel:0.6.25.4.1423
Show in Project Structure dialog
Affected Modules: app

Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugCompileClasspath'.
